[opener]
vim = [
  { run = "vim $@", block = true }
]

[open]
rules = [
  { mime = "text/*", use = "vim" },
  { name = "*.md", use = "vim" },
  { name = "*.sh", use = "vim" },
  { name = "*.toml", use = "vim" },
  { name = "*", use = "vim"}
]
